# -*- coding: utf-8 -*-
"""MVP Entrega Final - Machine Leaning Analytics - PUCRIO - Gabriel Lira .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Sd2cTb4_x9CYHbQeLFQfoojbIoipcaS

# **MVP — Machine Learning & Analytics**


**Nome:** _Gabriel Pinto de Lira do Nascimento_  
**Matrícula:** _4052026000244_  
**Data:** _05/07/2026_  
**Dataset:** _Coffee Quality Institute Arabica Reviews May2023_

https://www.kaggle.com/datasets/erwinhmtang/coffee-quality-institute-reviews-may2023/data  

**Tipo de problema:** _Classificação_

# 1. Definição do problema

## 1.1 Descrição do problema

Sou designer formado, mas sempre trabalhei com dados, fazendo apresentações e infográficos. Estou em transição de carreira, e por questão de afinidade, atualmente trabalho como analista de dados. O tema de machine learning foi um grande desafio de aprendizado. Como forma de tornar o assunto mais leve, e acima de tudo ter contexto: avalair os resultados exige entender o que é realmente relevante e extrair insights, escolhi Cafés Especiais como tema.



---



### **Contexto**
O mercado de cafés especiais é altamente valorizado e rigoroso. Para que um café receba o selo de "Especial", ele precisa atingir uma pontuação igual ou superior a 80 pontos (Total Cup Points) na avaliação da Specialty Coffee Association (SCA) / Coffee Quality Institute (CQI), e não possuir defeitos (categoria 1 de defeitos, a mais relevante) e até 5 efeitos na categoria 2.

O desafio é que essa nota final é obtida através de um processo de degustação sensorial (o cupping) feito por especialistas certificados (Q-Graders), o que ocorre apenas nas etapas finais da cadeia. Antes de virar bebida, o café é apenas um grão cru (verde) com características físicas, de plantio e de colheita.


---


### **Objetivo**

O modelo tem como objetivo principal apoiar a decisão de compra e precificação de lotes de café através de uma tarefa de **Classificação**. O algoritmo deve prever qual é a probabilidade de um lote de café cru ser classificado como "Especial" (Nota $\ge$ 80) baseando-se exclusivamente em suas características geográficas e físicas preliminares (como Altitude, País de Origem, Método de Processamento, Cor do grão e variedade do café), ou seja, sem a necessidade prévia da prova na xícara.


#### **Defeitos no café e origem**
Além disso existe um ponto importante, os defeitos no café tipo 1 dizem respeito mais ao cuidado (higiene) e ao processo de colheita e secagem do que da qualidade do grão em si. Os defeitos do tipo 2 dizem respeito ao momento certo de colheita, ou o grau de maturação.  Se a maturação for muito rapida, o café não tem tempo de ganhar caracteristicas importantes como sua doçura. Aqui a altitude ganha importância. Por isso esses atrubutos não vao ser utilizados no teste.

Como o país de origem tem forte relação com o processo e sua qualidade, assim como o defeito, retirei esses tres parametros para reduzir o viés, e foquei nas qualidades físicas preliminares. Cheguei a fazer um teste com o país de origem, e não obtive resultados muito bons (recall baixo, ou underfiting).



---


### **Grupo de interesse**

* **Compradores de Café Verde e Torrefações (Roasters):** Que precisam decidir quais lotes comprar e querem minimizar o risco de adquirir um café que não atinja o padrão de especialidade.

* **Produtores e Fazendeiros:** Que desejam entender o potencial da sua safra com base nos dados climáticos, geográficos e no processo de pós-colheita adotado na fazenda, antes mesmo de enviar o café para a avaliação de um especialista.

* **Cooperativas de Café:** Que precisam triar e categorizar rapidamente grandes volumes de sacas recebidas.


---


### **Relevância**

A avaliação sensorial humana é um processo caro, demorado e que exige mão de obra altamente especializada. Se o mercado puder estimar o potencial de qualidade de um lote de café de forma antecipada — olhando apenas para os dados técnicos da ficha do produtor (geografia e caracteristicas físicas do grão) —, é possível otimizar direcionar melhor os investimentos, antecipar a precificação correta de uma safra e focar em melhorar processos onde existem um potencial grande de se obter cafes especiais (e consequentimente de maior valor agregado).



---




### **Como um café é avaliado**

A Avaliação SCA/CQI é feita através de uma amostra padronizada, com cerca de 350g de grãos de café. Esta é a metodologia global para Cafés Especiais. O avaliador (Q Grader) pega uma amostra do café cru (verde). Ele mesmo faz uma torra clara, rigorosamente padronizada, e degusta a bebida (processo chamado de cupping).

O objetivo aqui é avaliar o potencial genético e o terroir (solo, clima, cuidado na colheita) do grão. A torra comercial pode "esconder" defeitos (se for muito escura) ou mascarar sabores. Ao padronizar uma torra clara apenas para a prova, o degustador consegue sentir exatamente o que aquele grão tem de bom (notas frutadas, florais) ou de ruim.


---

#Fonte
Os dados foram extraídos originalmente do portal do Coffee Quality Institute (CQI). O conjunto de dados contém pouco mais de 1.400 registros (linhas). Cada registro representa a avaliação de um lote específico de café cru (verde) enviado para o CQI. O dataset é rico com 48 colunas, unindo informações agronômicas (preenchidas pelo produtor) e avaliações sensoriais (realizadas por especialistas credenciados, os Q-Graders).


#Dicionário de Variáveis (Features e Atributos)
Abaixo está a descrição detalhada de todos os atributos presentes no dataset, divididos por categorias da cadeia de avaliação:

##1. Informações de Origem e Identificação (O Produtor)
Country_of_Origin: País onde os grãos de café foram cultivados.

* Farm_Name: Nome da fazenda produtora.

* Lot_Number: Número de identificação único do lote de café.

* Mill: Moinho ou instalação onde o café foi beneficiado/processado.

* ICO_Number: Número da Organização Internacional do Café (ICO) associado ao lote.

* Company: Empresa, cooperativa ou organização responsável pelo café.

* Altitude: Altitude (em metros) da lavoura.

* Region: Região geográfica ou província de produção.

* Producer: Indivíduo ou entidade produtora do café.

* Number_of_Bags: Quantidade total de sacas que compõem o lote.

* Bag_Weight: Peso individual de cada saca.

* In_Country_Partner: Parceiro local envolvido no processo de certificação.

* Harvest_Year: Ano da colheita/safra.

* Grading_Date: Data em que a avaliação (grading) foi realizada.

* Owner: Proprietário ou representante legal do lote.

* Variety: Variedade genética do grão (ex: Bourbon, Caturra, Geisha).

* Status: Status atual de processamento do lote.

* Processing_Method: Método de processamento pós-colheita utilizado (ex: Natural/Seco, Lavado/Washed, Cereja Descascado).

## 2. Análise Física do Grão Cru (Verde)
(Avaliação feita em uma amostra de 350g de café antes da torra)

* Moisture: Teor de umidade retido nos grãos crus.

* Color: Cor visual do grão cru (ex: Verde, Verde-azulado).

* Category_One_Defects: Contagem de defeitos primários (graves). Inclui grãos totalmente pretos, ardidos, "coco" (fruto seco inteiro), e gravetos ou pedras grandes. Para ser considerado Café Especial, este valor deve ser zero.

* Category_Two_Defects: Contagem de defeitos secundários (leves). Inclui grãos em pergaminho, quebrados, brocados (danos por insetos), parcialmente pretos/ardidos, conchas, e pequenos gravetos/pedras.

* Quakers: Número de grãos "quakers" encontrados. São grãos imaturos ou mal formados que não possuem açúcares suficientes para caramelizar durante a torra (ficam pálidos).

## 3. Notas de Avaliação Sensorial (Cupping)
(Notas atribuídas por especialistas após a torra e preparo da bebida, geralmente em uma escala até 10)

* Aroma: Avaliação do aroma do pó seco e da crosta formada pela água quente.
* Flavor (Sabor): Impressão principal do sabor do café na boca.
* Aftertaste (Finalização/Retrogosto): A duração e a qualidade do sabor que permanece na boca após engolir a bebida.
* Acidity: Qualidade da acidez (brilhante e agradável vs. azeda ou apagada).
* Body (Corpo): A sensação tátil, o peso ou a viscosidade do café na boca
* Balance (Equilíbrio): Como os aspectos de sabor, acidez e corpo se complementam e interagem.
* Uniformity (Uniformidade): Consistência do sabor entre as diferentes xícaras avaliadas do mesmo lote.
* Clean_Cup (Xícara Limpa): Mede a ausência de sabores negativos ou interferências não ligadas ao café (ex: gosto de terra, mofo).
* Sweetness (Doçura): Percepção agradável de doçura natural do grão.
* Overall (Impressão Geral): Nota pessoal do avaliador para a experiência total da amostra.
* Defects (duas categorias, sendo a um a mais relevante): Penalizações na nota geradas por defeitos sensoriais graves percebidos na xícara (taints/faults).
* Total_Cup_Points (Variável Alvo): A pontuação final somada do lote na avaliação (0 a 100 pontos). Lotes com pontuação $\ge 80$, e sem defeitos de grau 1 recebem o status de "Café Especial".

# **2. Carga e limpeza dos dados**


Durante a etapa de preparação dos dados, apliquei as seguintes técnicas de limpeza para garantir a qualidade da análise e a performance do modelo:

* Tratamento de Nulos: Valores ausentes em variáveis categóricas foram preenchidos com a categoria 'Unknown', enquanto os dados faltantes na coluna de altitude foram imputados utilizando a mediana.

* Padronização de Categorias: Realizamos tratamentos de strings (remoção de espaços, ajuste de maiúsculas/minúsculas) para agrupar categorias idênticas que possuíam grafias diferentes, reduzindo a alta cardinalidade e a dispersão.

* Remoção de Outliers: Um registro anômalo, com pontuação (Total Cup Points) inferior a 50, foi excluído. Essa remoção foi essencial para evitar distorções visuais nos gráficos e reduzir o ruído no treinamento do modelo."
"""

# Configuração para não exibir os warnings
import warnings
warnings.filterwarnings("ignore")

# Imports necessários
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split


import kagglehub # para importar o dataset café
from kagglehub import KaggleDatasetAdapter

from sklearn.model_selection import KFold # para preparar os folds da validação cruzada

from sklearn.ensemble import ExtraTreesClassifier # ExtraTrees, para a Importância de Atributos
from sklearn.feature_selection import SelectKBest # para a Seleção Univariada
from sklearn.feature_selection import f_classif # para o teste ANOVA da Seleção Univariada
from sklearn.feature_selection import RFE # para a Eliminação Recursiva de Atributos
from sklearn.linear_model import LogisticRegression # Regressão Logística, para a Eliminação Recursiva de Atributos



from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer, make_column_selector
from sklearn.preprocessing import StandardScaler, OneHotEncoder

from sklearn.preprocessing import StandardScaler

from sklearn.model_selection import GridSearchCV, train_test_split

from sklearn.ensemble import RandomForestClassifier # Substitua pelo seu modelo

from sklearn.metrics import roc_curve, auc, RocCurveDisplay



from sklearn.metrics import classification_report, accuracy_score, confusion_matrix, ConfusionMatrixDisplay

# Carga do dataset

path = kagglehub.dataset_download("erwinhmtang/coffee-quality-institute-reviews-may2023")
file_path = "arabica_coffee_full_table.csv"
df = pd.read_csv(f"{path}/{file_path}")



# Exibe o texto normal primeiro
print("Abaixo estão as 5 primeiras linhas do dataset de café:")

# Deixe este comando sozinho no final sem print() para ativar a tabela formatada
df.head(5)

"""Aqui para a altitude utilizei a moda, pois se os cafés são bons, provavelmente ou em sua maioria serão de altitudes mais elevadas.

Para os demais utilizei uma nova categoria, unknown.
"""

# 1. Visualizar a quantidade de nulos ANTES do tratamento
colunas_alvo = ['Country_of_Origin', 'Altitude', 'Variety', 'Processing_Method', 'Color']
print("--- Valores nulos ANTES do tratamento ---")
print(df[colunas_alvo].isnull().sum())

# ==========================================
# TRATAMENTO DA VARIÁVEL NUMÉRICA (Altitude)
# ==========================================




# Preenche os valores nulos da Altitude com a MEDIANA (menos sensível a
# outliers que a média)
mediana_altitude = df['Altitude'].median()
df['Altitude'] = df['Altitude'].fillna(mediana_altitude)

# Retirar outlier com nota zero

df = df[df['Total_Cup_Points'] >= 50].copy()


# ==========================================
# TRATAMENTO DAS VARIÁVEIS CATEGÓRICAS
# ==========================================

# Para Country_of_Origin, Processing_Method e Color: vamos preencher com a MODA (valor mais frequente)
for col in ['Country_of_Origin', 'Processing_Method', 'Color']:
    df[col] = df[col].fillna('Unknown')

# Para Variety: Como existem muitas variedades diferentes, criar uma categoria "Desconhecido"
# costuma ser uma boa prática de ML para não distorcer o dado enviesando para a variedade mais comum.
df['Variety'] = df['Variety'].fillna('Unknown')


# 2. Visualizar a quantidade de nulos DEPOIS do tratamento
print("\n--- Valores nulos DEPOIS do tratamento ---")
print(df[colunas_alvo].isnull().sum())

# 1. Verificando os valores únicos ANTES da limpeza
print("--- Cores antes da limpeza ---")
print(df['Color'].value_counts(dropna=False))

# 2. Função para padronizar as cores
def padronizar_cor(cor):
    # Se for nulo, deixa como nulo por enquanto (você pode tratar com a Moda depois)
    if pd.isna(cor):
        return cor

    # Converte para string, tudo minúsculo e remove espaços nas pontas
    cor_str = str(cor).lower().strip()

    # Remove hífens e junta espaços extras (ex: 'yellow - green' vira 'yellow green')
    cor_str = cor_str.replace('-', ' ')
    cor_str = ' '.join(cor_str.split())

    # Agrupamento Lógico
    if cor_str in ['yellow green', 'yellowish green', 'green yellow']:
        return 'Yellow-Green'

    elif cor_str in ['blue green', 'bluish green', 'green blue']:
        return 'Blue-Green'

    elif 'green' in cor_str: # Se for apenas verde ou alguma variação solta
        return 'Green'

    elif cor_str == 'none':
        # Na base do CQI, "None" significa que não souberam classificar a cor
        return 'Desconhecido'

    else:
        # Para qualquer outra cor, apenas deixa a primeira letra maiúscula (ex: 'brown' -> 'Brown')
        return cor_str.title()

# 3. Aplicando a transformação na coluna
df['Color'] = df['Color'].apply(padronizar_cor)

# 4. Verificando os valores únicos DEPOIS da limpeza
print("\n--- Cores DEPOIS da limpeza ---")
print(df['Color'].value_counts(dropna=False))

"""# **3. Exploratory data analysis** (EDA)

**Análise do Desbalanceamento de Classes:**
A análise das distribuições revela uma assimetria acentuada em diversas variáveis, o que sinaliza um desafio importante para a modelagem preditiva. Identificamos um severo desbalanceamento de classes na variável alvo, com uma clara disparidade entre cafés especiais e as demais categorias. Observa-se comportamento semelhante nos atributos de Cor e Método de Processamento, onde há uma predominância absoluta de grãos 'Green' e métodos 'Washed/Wet'. Em contrapartida, a variável Variedade (do grão) apresenta uma distribuição mais equilibrada, o que sugere um potencial maior de generalização do modelo para este atributo. O desbalanceamento identificado será um ponto crítico a ser considerado, exigindo métricas de avaliação robustas para evitar o viés de predição em favor da classe majoritária.

Separei a visualização exploratória em duas partes:
* grafico de barra para visualizar as quantidades por categoria
* Scatterplot: para entender a distribuição dos valores, por altitude, um critério muito relevante, **pois em altitudes maiores e consequentemente temperaturas mais amenas, o café matura mais lentamente, o que agrega qualidade em suas caracteristicas sensoriais.**
"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np



# Configuração visual padrão para ficar bonito no MVP
sns.set_theme(style="whitegrid")

# ==============================================================================
# 1. Gráfico de Barras: Cor do Grão
# ==============================================================================
plt.figure(figsize=(10, 5))
# O argumento 'order' garante que a barra maior fique primeiro (ordem decrescente)
ordem_cores = df['Color'].value_counts().index

sns.countplot(data=df, x='Color', order=ordem_cores, palette='viridis')
plt.title('Quantidade de Amostras por Cor do Grão cru', fontsize=14)
plt.xlabel('Cor', fontsize=12)
plt.ylabel('Quantidade de Amostras', fontsize=12)
plt.show()

# ==============================================================================
# 2. Gráfico de Barras: Variedade (Top 10)
# ==============================================================================
plt.figure(figsize=(12, 5))
# Como existem muitas variedades, vamos pegar apenas as 10 mais frequentes para o gráfico não virar um borrão
top_variedades = df['Variety'].value_counts().nlargest(10).index
df_variedades = df[df['Variety'].isin(top_variedades)]

sns.countplot(data=df_variedades, x='Variety', order=top_variedades, palette='viridis')
plt.title('Quantidade de Amostras por Variedade (Top 10)', fontsize=14)
plt.xlabel('Variedade', fontsize=12)
plt.ylabel('Quantidade de Amostras', fontsize=12)
plt.xticks(rotation=45, ha='right') # Rotaciona os nomes para caberem bonitinho
plt.show()

# ==============================================================================
# 3. Gráfico de Barras: Método de Processamento
# ==============================================================================
plt.figure(figsize=(12, 5))
ordem_processamento = df['Processing_Method'].value_counts().index

sns.countplot(data=df, x='Processing_Method', order=ordem_processamento, palette='viridis')
plt.title('Quantidade de Amostras por Método de Processamento', fontsize=14)
plt.xlabel('Método', fontsize=12)
plt.ylabel('Quantidade de Amostras', fontsize=12)
plt.xticks(rotation=45, ha='right')
plt.show()

# ==============================================================================
# 4. Gráfico de Barras: Cafés Especiais vs Não Especiais
# ==============================================================================
# Primeiro, criamos uma coluna apenas com os textos para ficar bonito no gráfico
# Critério: Nota >= 80 e 0 defeitos de categoria 1
df['Classe_Qualidade'] = np.where(
    (df['Total_Cup_Points'] >= 80) & (df['Category_One_Defects'] == 0) & (df['Category_Two_Defects'] <= 5),
    'Café Especial (Premium)',
    'Café Não Especial'
)

plt.figure(figsize=(8, 5))
sns.countplot(data=df, x='Classe_Qualidade', palette={'Café Especial (Premium)': '#B72818', 'Café Não Especial': '#1D3ECF'})
plt.title('Proporção de Cafés Especiais no Dataset', fontsize=14)
plt.xlabel('Classificação', fontsize=12)
plt.ylabel('Quantidade de Amostras', fontsize=12)
plt.show()

# Configurando o estilo visual dos gráficos para ficar mais profissional
sns.set_theme(style="whitegrid")

# ==============================================================================
# Gráfico 1: Altitude vs Total Cup Points (Destacando Especiais e Sem Defeitos)
# ==============================================================================
plt.figure(figsize=(10, 6))

# Criando uma coluna temporária apenas para a regra de destaque
df['Destaque_Especial'] = np.where(
    (df['Total_Cup_Points'] >= 80) & (df['Category_One_Defects'] == 0 ) & (df['Category_Two_Defects'] <= 5 ),
    'Especial & Zero Defeitos (Cat 1 e 2)',
    'Outros'
)

sns.scatterplot(data=df, x='Altitude', y='Total_Cup_Points',
                hue='Destaque_Especial', palette=['#B72818', '#1D3ECF'],
                alpha=0.4, s=60)

plt.title('Altitude vs Qualidade: Foco nos Cafés de Excelência Física', fontsize=14)
plt.xlabel('Altitude (metros)', fontsize=12)
plt.ylabel('Total Cup Points', fontsize=12)
plt.legend(title='Classificação')
plt.show()

# ==============================================================================
# Gráfico 2: Altitude vs Total Cup Points (Colorindo por Cor do Grão)
# ==============================================================================
plt.figure(figsize=(10, 6))
sns.scatterplot(data=df, x='Altitude', y='Total_Cup_Points',
                hue='Color', palette='Set2', alpha=0.7, s=60)

plt.title('Altitude vs Qualidade por Cor do Grão Verde', fontsize=14)
plt.xlabel('Altitude (metros)', fontsize=12)
plt.ylabel('Total Cup Points', fontsize=12)
plt.legend(title='Cor do Grão')
plt.show()

# ==============================================================================
# Gráfico 3: Altitude vs Total Cup Points (Colorindo por Variety)
# ==============================================================================
# DICA: Como 'Variety' tem muitas opções, vamos pegar apenas as 5 mais comuns
# para o gráfico não virar uma "salada de frutas" ilegível.
top_varieties = df['Variety'].value_counts().nlargest(5).index
df_top_varieties = df[df['Variety'].isin(top_varieties)]

plt.figure(figsize=(10, 6))
sns.scatterplot(data=df_top_varieties, x='Altitude', y='Total_Cup_Points',
                hue='Variety', palette='tab10', alpha=0.7, s=60)

plt.title('Altitude vs Qualidade (Top 5 Variedades)', fontsize=14)
plt.xlabel('Altitude (metros)', fontsize=12)
plt.ylabel('Total Cup Points', fontsize=12)
plt.legend(title='Variedade', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout() # Ajusta para a legenda não cortar
plt.show()

# ==============================================================================
# Gráfico 4: Altitude vs Total Cup Points (Colorindo por Processing_Method)
# ==============================================================================
plt.figure(figsize=(10, 6))
sns.scatterplot(data=df, x='Altitude', y='Total_Cup_Points',
                hue='Processing_Method', palette='Dark2', alpha=0.7, s=60)

plt.title('Altitude vs Qualidade pelo Método de Processamento', fontsize=14)
plt.xlabel('Altitude (metros)', fontsize=12)
plt.ylabel('Total Cup Points', fontsize=12)
plt.legend(title='Método', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

# ==============================================================================
# Gráfico 5: Altitude vs Total Cup Points (Colorindo por Bins de Moisture)
# ==============================================================================
plt.figure(figsize=(10, 6))

# Criando as 4 faixas (bins) de umidade
df['Moisture_Bins'] = pd.qcut(df['Moisture'], q=4, labels=['Muito Baixa', 'Baixa', 'Média', 'Alta'], duplicates='drop')

sns.scatterplot(data=df, x='Altitude', y='Total_Cup_Points',
                hue='Moisture_Bins', palette='coolwarm', alpha=0.7, s=60)

plt.title('Altitude vs Qualidade por Faixas de Umidade', fontsize=14)
plt.xlabel('Altitude (metros)', fontsize=12)
plt.ylabel('Total Cup Points', fontsize=12)
plt.legend(title='Umidade (Moisture)')
plt.show()

"""# **4. Target**

O Target são os cafés com o Total Cup Points maior que 80 e sem nenhum defeito de categoria um (mais relevantes).
"""

# 2. CONSTRUINDO O TARGET COM MÚLTIPLOS CRITÉRIOS
# Regra do Café Especial: Nota >= 80 E Zero Defeitos de Categoria 1
criterio_nota = df['Total_Cup_Points'] >= 80
criterio_defeitos_1 = df['Category_One_Defects'] == 0
criterio_defeitos_2 = df['Category_One_Defects'] <= 5

# Junta as duas regras usando o operador & (AND) e converte para 1 e 0
df['target'] = (criterio_nota & criterio_defeitos_1 & criterio_defeitos_2).astype(int)

# 3. Exibe o resultado (mostrando só as colunas que importam para conferir)
df[['Total_Cup_Points', 'Category_One_Defects', 'target']].head(10)

"""Montagem do dataset

1 = Café Especial: Como o Python converte True (verdadeiro) para 1, e a condição é Total_Cup_Points >= 80.0, todos os cafés com nota igual ou superior a 80 tornam-se a Classe 1.

0 = Não Especial (ou Comercial): Como o Python converte False (falso) para 0, todos os cafés com nota abaixo de 80 tornam-se a Classe 0.
"""

# -------------------------------------------------------------------
# 1. APLICAR FILTRO DE ESPECIALISTA (Remover defeitos graves)
# -------------------------------------------------------------------
df_clean = df[
    (df['Category_One_Defects'] == 0) &
    (df['Category_Two_Defects'] <= 5)
].copy()

# -------------------------------------------------------------------
# 2. DEFINIR AS COLUNAS
# -------------------------------------------------------------------
# Dica: Verifique se você está usando 'Altitude' ou 'altitude_clean'
# dependendo do tratamento que fez anteriormente.
features = [
    'Altitude',              # 0
    'Moisture',              # 1
    'Variety',               # 2
    'Color',                 # 3
    'Processing_Method'     # 4
]

# 3. Montar o "dataset limpo" usando o df_clean
dataset_modelo = df_clean[features].copy()
dataset_modelo['target'] = (df_clean['Total_Cup_Points'] >= 80.0).astype(int) # Classe Alvo

# -------------------------------------------------------------------
# 4. PREPARAÇÃO DOS DADOS - ADAPTADO PARA O PIPELINE
# -------------------------------------------------------------------
# Usamos os DataFrames diretamente (sem .values) para não perder
# os nomes das colunas (exigência do ColumnTransformer).

X = dataset_modelo[features]  # Atributos (X continuará sendo um DataFrame)
y = dataset_modelo['target']  # Classe/Target (y continuará sendo uma Series)

# Fazer a divisão com estratificação para manter a proporção da classe alvo
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=7, stratify=y
)

# Criar os folds para a validação cruzada
num_particoes = 10
kfold = KFold(n_splits=num_particoes, shuffle=True, random_state=7)

print("--- Divisão Concluída com Sucesso ---")
print(f"X_train possui {X_train.shape[0]} linhas e {X_train.shape[1]} colunas.")

"""# 5. Primeiro teste de Classificação (Holdout)"""

# -------------------------------------------------------------------
# 1. CRIANDO O TRANSFORMADOR (O "Tradutor" para o Algoritmo)
# -------------------------------------------------------------------
# Como usamos dataset.values, perdemos os nomes. Usamos as posições
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), [0, 1]), # Somente as colunas numéricas aqui!
        # sparse_output=False é obrigatório aqui para o modelo Naive Bayes (NB) funcionar
        ('cat', OneHotEncoder(handle_unknown='ignore', sparse_output=False), [2, 3, 4])
    ])

# -------------------------------------------------------------------
# 2. PREPARANDO OS MODELOS
# -------------------------------------------------------------------
np.random.seed(7) # Seed global

models = []
results = []
names = []

# Adicionamos os modelos dentro de um Pipeline.
# O fluxo é: Passo 1 ('prep') -> Passo 2 ('clf' - classificador)
models.append(('KNN', Pipeline([('prep', preprocessor), ('clf', KNeighborsClassifier())])))
models.append(('CART', Pipeline([('prep', preprocessor), ('clf', DecisionTreeClassifier(random_state=7))])))
models.append(('NB', Pipeline([('prep', preprocessor), ('clf', GaussianNB())])))
models.append(('SVM', Pipeline([('prep', preprocessor), ('clf', SVC(random_state=7))])))

# -------------------------------------------------------------------
# 3. TREINAMENTO E VALIDAÇÃO CRUZADA
# -------------------------------------------------------------------
print("Iniciando o treinamento e avaliação dos modelos...\n")

for name, model in models:
    # A validação cruzada usa os folds (kfold) que criamos na célula anterior
    cv_results = cross_val_score(model, X_train, y_train, cv=kfold, scoring='accuracy')
    results.append(cv_results)
    names.append(name)

    msg = "%s: Acurácia Média = %f (Desvio = %f)" % (name, cv_results.mean(), cv_results.std())
    print(msg)

# -------------------------------------------------------------------
# 4. VISUALIZAÇÃO - BOXPLOT
# -------------------------------------------------------------------
fig = plt.figure(figsize=(10, 6)) # Deixei o gráfico um pouco maior e mais elegante
fig.suptitle('Comparação da Acurácia dos Modelos de Machine Learning', fontsize=14)
ax = fig.add_subplot(111)

# O patch_artist e os boxprops ajudam a deixar o gráfico mais bonito e moderno
plt.boxplot(results, patch_artist=True, boxprops=dict(facecolor="lightblue"))

ax.set_xticklabels(names, fontsize=12)
plt.ylabel('Acurácia (0 a 1)', fontsize=12)
plt.grid(axis='y', linestyle='--', alpha=0.7) # Grade sutil para ajudar a leitura
plt.show()

"""# Avaliação dos resultados:

Tanto o SVM (93%) quanto o KNN (92%) tiveram desempenhos excelentes e muito parecidos.

* SVM: Teve a maior acurácia média absoluta, conseguindo traçar muito bem as fronteiras de decisão entre as classes.

* KNN: Ganhou na estabilidade. Ele teve o menor desvio padrão de todos (apenas ~1.5%), o que significa que, independente de como os dados foram divididos no teste, a performance dele quase não variou.


* CART: Com ~87% de acurácia, não é um resultado ruim, mas o desvio padrão quase chegando em 4% mostra que o modelo está um pouco instável. Árvores de decisão são naturalmente propensas a sofrer de overfitting (decorar os dados de treino) e tendem a variar muito dependendo dos dados que recebem em cada quebra.

* Naive Bayerw: Uma acurácia de ~37% indica que o modelo colapsou. O Naive Bayes parte de uma premissa muito forte: ele assume que todas as features são matematicamente independentes umas das outras, o que não é o caso do café.

# **6. Teste com o Modelo Vencedor (SVM)**

---



Esse bloco separa as informações em dois grupos (colunas de texto e colunas de números) e aplica o tratamento correto para cada um: transforma categorias de texto em números que o computador entende e padroniza as escalas dos valores numéricos, garantindo que variáveis de magnitudes diferentes não "atropelem" o aprendizado do modelo.

Ao unir esse tratamento e o modelo SVM dentro de um Pipeline, garante que qualquer novo dado passe exatamente pelo mesmo processo de preparação, evitando erros. Além disso, o parâmetro class_weight='balanced' é um "ajuste fino" essencial: ele avisa ao seu modelo para dar mais atenção aos cafés "Especiais" (que são mais raros no dataset), impedindo que o sistema foque apenas na classe majoritária e perca os padrões importantes de qualidade.
"""

# Selecione apenas as colunas que são categóricas (texto)
# e converta para colunas numéricas (0 ou 1)
df_encoded = pd.get_dummies(df, columns=['Color', 'Variety', 'Processing_Method'])

# Agora o seu df_encoded só tem números!
# Verifique se ainda há alguma coluna do tipo 'object' (string)
print(df_encoded.dtypes)

# X será tudo, menos a sua coluna alvo
X = df_encoded.drop('target', axis=1) # Ajuste 'target' para o nome da sua coluna alvo
y = df_encoded['target']

# Agora sim, o split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 1. Definição das colunas
cat_cols = ['Color', 'Variety', 'Processing_Method']
num_cols = ['Altitude', 'Moisture']

# 2. Preparação dos dados (Certifique-se de que 'df' é o seu dataframe limpo)
# Selecionamos apenas as features necessárias e garantimos que X é um DataFrame
X = df[cat_cols + num_cols]
y = df['target'] # Substitua 'target' pelo nome da sua coluna de classificação (ex: 'Quality_Class')

# 3. Divisão Treino/Teste
# Ao passar o DataFrame X aqui, o X_train e X_test retornam como DataFrames
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 4. Configuração do Preprocessor
# handle_unknown='ignore' é importante para evitar erros caso apareça uma categoria nova
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), num_cols),
        ('cat', OneHotEncoder(handle_unknown='ignore'), cat_cols)
    ])

# 5. Criação do Pipeline
svm_model = Pipeline([
    ('preprocessor', preprocessor),
    ('svc', SVC(kernel='rbf', probability=True, class_weight='balanced'))
])

# 6. Treinamento
# Agora que X_train é um DataFrame, o ColumnTransformer reconhecerá os nomes das colunas
svm_model.fit(X_train, y_train)

print("Modelo treinado com sucesso!")

"""Ajustei acima o hiperparametro class_weight = Balanced, para melhorar o recall, fiz direto para reduzir a quantidade de codigo, mas explico no texto. No caso o recall aumentou e a acuracia caiu, ou seja, seleciono melhor os cafes especiais, embora a acuracia media tenha caido."""

# 1. Gerar as predições com o seu modelo já treinado
y_pred = svm_model.predict(X_test)

# 2. Calcular a acurácia
acc = accuracy_score(y_test, y_pred)
print(f"Acurácia Final do Modelo: {acc:.2%}")

# 3. Gerar a Matriz de Confusão (o seu gráfico de performance)
cm = confusion_matrix(y_test, y_pred)

# 4. Plotar o gráfico
fig, ax = plt.subplots(figsize=(8, 6))
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=svm_model.classes_)
disp.plot(cmap='Blues', ax=ax)

plt.title('Matriz de Confusão (SVM)')
plt.show()

# Imprimir o relatório detalhado
print("\n--- RELATÓRIO DE CLASSIFICAÇÃO ---")
print(classification_report(y_test, y_pred))

"""Avaliação dos resultados

Resultado antes de ajustar o balanceamento forçado do SVM foi de 81%, mas com forte desbalaneamento, para reduzir apliquei esse recurso e obtive um resultado menos desbalanceado a acurácia foi de 67,55%.


A Matriz de Confusão:

* 168 (Verdadeiros Positivos): Cafés especiais que ele acertou que eram especiais.

* 36 (Verdadeiros Negativos): Cafés comuns (Classe 0) que ele acertou que eram comuns.

* 79 (Falsos Negativos): O grande calcanhar de Aquiles do modelo atual. Ele pegou 82 cafés que eram especiais e disse: "Isso é café não especial".

* 19 (Falsos Positivos): Ele pegou 19 cafés comuns e disse: "Isso é café especial".


---


**Durante a etapa de otimização, realizei um teste de controle entre o modelo baseline e o modelo ajustado com class_weight='balanced'. Embora a acurácia global tenha reduzido de 82% para 66,5%, este foi um trade-off deliberado.**

No modelo original, o Recall da classe minoritária (Cafés Especiais) era de apenas 13%, tornando o modelo ineficaz para o objetivo de negócio. Ao balancear as classes, elevamos o Recall da classe especial para 65%. Ou seja, passamos a identificar a vasta maioria dos lotes de alta qualidade. Para o nosso MVP, a prioridade **é a capacidade de descoberta (Recall)** e não a acurácia bruta, pois o custo de ignorar um lote de café especial é superior ao custo de uma falsa classificação em um lote comum.

# **7. Seleção dos melhores atributos para SVM**

Apliquei a seleção automática de atributos (SelectKBest) e configurei o modelo Random Forest com tratamento para desbalanceamento. Por fim, utilizei: o GridSearchCV para buscar, de forma exaustiva e cruzada, o melhor número de features ($k$) que maximiza a acurácia, para buscar garantir um modelo mais robusto
"""

# 1. Configuração do Pré-processamento
# Identifica colunas categóricas (texto) e numéricas automaticamente
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), make_column_selector(dtype_include=['number'])),
        ('cat', OneHotEncoder(handle_unknown='ignore'), make_column_selector(dtype_include=['object', 'category']))
    ]
)

# 2. Montagem do Pipeline

pipe = Pipeline([
    ('preprocessor', preprocessor),
    ('selector', SelectKBest(score_func=f_classif, k=10)),
    ('model', RandomForestClassifier(random_state=42))
])

# 3. Definição do Grid de Busca
# Ajuste o range de 'k' conforme o número total de suas colunas após o OneHotEncoder
params = {
    'selector__k': [2, 3, 4, 5, 6, 8, 10]
}

# 4. Execução
grid = GridSearchCV(pipe, param_grid=params, cv=5, scoring='accuracy', n_jobs=-1)
grid.fit(X, y)

# 5. Resultados
print(f"Melhor número de features (k): {grid.best_params_['selector__k']}")
print(f"Melhor pontuação (Acurácia): {grid.best_score_:.3f}")

# Exibir quais colunas foram selecionadas
# Isso é importante para entender o que o modelo está valorizando
print("\nMelhor Pipeline:")
print(grid.best_estimator_)

# Acessa o melhor estimador encontrado pelo GridSearch
best_pipe = grid.best_estimator_

# Acessa o seletor dentro do pipeline
selector = best_pipe.named_steps['selector']

# Acessa o pré-processador para obter os nomes das colunas após a transformação
preprocessor = best_pipe.named_steps['preprocessor']

# Pega os nomes das colunas transformadas
feature_names = preprocessor.get_feature_names_out()

# Pega os nomes das 2 selecionadas
selected_features = selector.get_feature_names_out(feature_names)

print("As features que o modelo mais valoriza são:")
print(selected_features)

# Prevendo com o melhor modelo
y_pred = grid.best_estimator_.predict(X)

# Exibindo métricas detalhadas
print(classification_report(y, y_pred))

# Plotando a Matriz de Confusão
cm = confusion_matrix(y, y_pred)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.title("Matriz de Confusão do Modelo Final")
plt.show()

"""**Ao tentar simplificar o modelo, removi as variáveis que carregavam a essência da qualidade do café, tive perda de qualidade na discriminação dos dados.**

Isso prova empiricamente que a separação entre café Especial e Comercial em nosso dataset não é linear e exige a manutenção da alta dimensionalidade original. Em vez de uma simplificação agressiva, este resultado me levou a reavaliar o pipeline, optando por manter o conjunto completo de atributos e focar em técnicas de rebalanceamento, como o ajuste de pesos das classes (class_weight='balanced'), para garantir que o modelo ganhe sensibilidade para a classe minoritária sem sacrificar a complexidade necessária para a classificação


---


* Classe 1 (Especial): Recall de 0.97. Isso é excelente para capturar cafés especiais, mas o valor alto pode ser um sinal de que ele está classificando quase tudo como Especial.

* Classe 0 (Comercial): Recall de 0.16. Este é o ponto crítico. O modelo só consegue identificar 16% dos cafés que são realmente "Comerciais". Ele está errando 84% dos cafés comerciais, classificando-os erroneamente como Especiais.

* Acurácia (0.78): Como você tem 1.169 casos da Classe 1 e apenas 339 da Classe 0, o modelo descobriu que "chutar" que tudo é Classe 1 é a estratégia estatisticamente mais segura para manter a acurácia alta, mesmo que o modelo seja inútil na prática para identificar cafés comerciais.

## 8. Random Forest

SVM: É um modelo que busca uma linha (ou hiperplano) de separação. É ótimo, mas às vezes sofre se os dados forem muito complexos ou não lineares.

Random Forest: É um modelo de Ensemble (conjunto). Ele cria várias árvores de decisão e tira a "média" delas. Ele é extremamente robusto, lida muito bem com dados desbalanceados (teoricame)
"""

# 1. Split dos dados (80% treino, 20% teste)
# Isso garante que o modelo seja avaliado em dados que ele nunca viu
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# 2. Pipeline com ajuste de peso balanceado
# Mantemos o class_weight='balanced' para mitigar o viés das classes
pipe = Pipeline([
    ('preprocessor', preprocessor),
    ('selector', SelectKBest(score_func=f_classif)),
    ('model', RandomForestClassifier(random_state=42, class_weight='balanced'))
])

# 3. Busca ampla de hiperparâmetros
# Testamos mais opções de k para dar mais liberdade ao modelo
params = {
    'selector__k': [2, 3, 4, 5, 6, 8, 10, 12]
}

# 4. Execução (agora no conjunto de treino)
grid = GridSearchCV(pipe, param_grid=params, cv=5, scoring='f1_macro', n_jobs=-1)
grid.fit(X_train, y_train)



# 5. Avaliação final no conjunto de TESTE
best_model = grid.best_estimator_
y_pred = best_model.predict(X_test)

print(f"Melhor K encontrado: {grid.best_params_['selector__k']}")
print("\nRelatório de Classificação (Dados de Teste):")
print(classification_report(y_test, y_pred))

# Plot da Matriz de Confusão para visualizar onde o modelo erra
plt.figure(figsize=(6,4))
sns.heatmap(confusion_matrix(y_test, y_pred), annot=True, fmt='d', cmap='Blues')
plt.title("Matriz de Confusão - Dados de Teste")
plt.xlabel("Predito")
plt.ylabel("Real")
plt.show()

"""**Resultado sofre de underfiting, ou seja falta de complexidade.**


---


Ao reduzir o dataset a apenas 3 colunas, provavelmente descartei informações vitais que o modelo precisava para diferenciar o "Café Especial" do "Não comercial". O Random Forest é um algoritmo que precisa de um pouco mais de "contexto" (features) para construir árvores de decisão que façam sentido.

A performance superior do SVM (anteriormente testado) confirma que ele é mais robusto em mapear essas relações multidimensionais, enquanto o Random Forest, com essa restrição de features, não conseguiu generalizar adequadamente. Portanto, a escolha do SVM como modelo final não foi apenas intuitiva, mas validada por esse comparativo de robustez.
"""

# ==========================================
# TESTE 2: Gradient Boosting para Classes Desbalanceadas
# ==========================================

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer, make_column_selector
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.metrics import classification_report, confusion_matrix

# 1. Separação de Treino e Teste (Garantindo a proporção das classes com stratify)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# 2. Configuração do Pré-processamento Dinâmico
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), make_column_selector(dtype_include=['number'])),
        ('cat', OneHotEncoder(handle_unknown='ignore', sparse_output=False), make_column_selector(dtype_include=['object', 'category']))
    ],
    remainder='passthrough'
)

# 3. Construção do Pipeline com o Novo Modelo
# O HistGradientBoosting é extremamente rápido e lida bem com dados complexos
pipe_gb = Pipeline([
    ('preprocessor', preprocessor),
    ('selector', SelectKBest(score_func=f_classif, k=4)), # Mantivemos k=4 para começar
    ('model', HistGradientBoostingClassifier(random_state=42, class_weight='balanced'))
])

# 4. Treinamento do Modelo
print("Treinando o modelo Gradient Boosting...")
pipe_gb.fit(X_train, y_train)

# 5. Avaliação com Dados Inéditos (Teste)
y_pred_gb = pipe_gb.predict(X_test)

# 6. Exibição dos Resultados Comparativos
print("\n" + "="*40)
print("RELATÓRIO DE CLASSIFICAÇÃO: GRADIENT BOOSTING")
print("="*40)
print(classification_report(y_test, y_pred_gb))

# 7. Visualização (Matriz de Confusão)
plt.figure(figsize=(7, 5))
cm = confusion_matrix(y_test, y_pred_gb)
sns.heatmap(cm, annot=True, fmt='d', cmap='Oranges', cbar=False)
plt.title("Matriz de Confusão - Gradient Boosting", pad=15, fontsize=14)
plt.ylabel("Classe Real (SCA/ABIC)", fontsize=11)
plt.xlabel("Classe Predita", fontsize=11)
plt.tight_layout()
plt.show()

# 8. Extração das Features Selecionadas
preprocessor_fitted = pipe_gb.named_steps['preprocessor']
selector_fitted = pipe_gb.named_steps['selector']
feature_names = preprocessor_fitted.get_feature_names_out()
selected_features = selector_fitted.get_feature_names_out(feature_names)

print("\nAs 4 features mais importantes selecionadas para este modelo foram:")
for feat in selected_features:
    print(f"- {feat.replace('num__', '').replace('cat__', '')}")

"""Durante a etapa de seleção de modelos, realizei um comparativo entre o SVM (meu modelo campeão) e algoritmos baseados em árvores (Random Forest e Gradient Boosting). Interessantemente, o desempenho dos modelos de árvore caiu drasticamente quando apliquei uma redução rigorosa de dimensionalidade (3 features).

Isso provou, empiricamente, que o nosso dataset não possui uma separação linear simples e que as interações entre as variáveis (geográficas e físicas) são complexas. O SVM, por utilizar o Kernel Trick (RBF), consegue mapear essas relações multidimensionais em um espaço de características superior

Já os modelos de árvore, ao serem privados de um conjunto maior de atributos, sofreram de underfitting — eles não tinham 'contexto' suficiente nas árvores para realizar as divisões de forma precisa.

Portanto, a escolha pelo SVM não foi arbitrária. Ela foi validada pela incapacidade de modelos alternativos de generalizarem o padrão de qualidade do café sob as mesmas restrições, confirmando que o SVM é o modelo mais estável e adequado para a complexidade intrínseca dos dados agronômicos que estamos analisando.
"""

# Calcular a probabilidade (o SVM precisa de probability=True no fit para isso)
# Se o seu SVM não tiver probability=True, use o decision_function
y_score = svm_model.decision_function(X_test)

fpr, tpr, thresholds = roc_curve(y_test, y_score)
roc_auc = auc(fpr, tpr)

# Plotar
plt.figure(figsize=(8, 6))
plt.plot(fpr, tpr, label=f'SVM (AUC = {roc_auc:.2f})')
plt.plot([0, 1], [0, 1], linestyle='--', color='r', label='Aleatório (0.50)')
plt.xlabel('Taxa de Falsos Positivos')
plt.ylabel('Taxa de Verdadeiros Positivos (Recall)')
plt.title('Curva ROC - Validação do Modelo SVM')
plt.legend()
plt.show()

"""O modelo tem 69% de probabilidade de classificar corretamente um par de café escolhido aleatoriamente

# 9. Conclusões

* 1. Objetivo do Trabalho
O objetivo deste projeto foi desenvolver um modelo de Machine Learning capaz de classificar a qualidade de lotes de café como "Especial" (pontuação $\ge$ 80), sem defeitos de categoria 1, e até 5 de categoria 2. A estratégia deste trabalho foi a construção de um modelo focado na visão do produtor e do comprador pré-colheita, eliminando intencionalmente as notas sensoriais (cupping notes) para evitar o data leakage (vazamento de dados), o que garante que o modelo avalie padrões reais de produção e não apenas uma somatória matemática de notas de degustação.

* 2. Melhor Solução Encontrada
A melhor solução obtida foi o modelo de Support Vector Machine (SVM) com Kernel RBF. A escolha por este algoritmo justifica-se pela sua capacidade de encontrar fronteiras de decisão não-lineares, essenciais em dados agronômicos onde a qualidade não evolui de forma linear com a altitude ou o processamento. O modelo foi integrado a um Pipeline de pré-processamento (via ColumnTransformer), que tratou automaticamente a normalização de variáveis numéricas e a codificação de categóricas, garantindo a reprodutibilidade

* 3. Comparação com Baseline:
O SVM superou outros modelos testados, como Naive Bayes e KNN. Enquanto o Naive Bayes falhou devido à alta correlação entre variáveis explicativas (violando sua premissa de independência), o SVM demonstrou maior robustez ao lidar com a dimensionalidade e a não-linearidade dos dados. O comparativo validou que a complexidade do problema exige um modelo capaz de mapear interações multidimensionais entre o terroir e o manejo do café.

* 4. Tratamento de Desbalanceamento: em um dataset desbalanceado, a acurácia é uma métrica ilusória. A utilização de métricas como F1-Score e Recall, aliada ao ajuste de pesos das classes (class_weight='balanced'), foi fundamental para que o modelo priorizasse a identificação da classe de cafés especiais no modelo de teste.

* 5. Limitações
A principal limitação reside na natureza inerente do dataset, que apresenta um desbalanceamento natural. Embora o ajuste de pesos tenha mitigado o viés, a precisão na classe minoritária ainda enfrenta desafios.

* 6. Viés: olhando a base e vendo Quais paises se relacionam com Unknowm ou Blue-green no que diz respeito a cor do grão, existe um forte vies geografico de um grupo de paises (Brasil, mexico, colombia) por exemplo. Mesmo tirando a questão geografica para a classificaão ser mais balanceada, isso se mostrou um grande desafio.

# 9.1 Resultados Comparados

* SVM (Baseline):
Este modelo revelou-se o mais equilibrado, com Recalls de 65% (classe 0) e 68% (classe 1). Esta simetria demonstra uma capacidade sólida de generalização, evitando o vício na classe majoritária e confirmando a eficácia do SVM no mapeamento das fronteiras de decisão deste dataset.

* SVM com Feature Selection:
A seleção de atributos comprometeu o desempenho, gerando um modelo enviesado com 16% de Recall na classe 0 e 97% na classe 1. Este resultado comprova empiricamente que as variáveis removidas eram preditores cruciais, e que simplificações agressivas invalidam a capacidade do modelo de distinguir cafés especiais.

* Random Forest:
O modelo apresentou um comportamento conservador, registando 29% de Recall na classe 0 e 76% na classe 1. A dificuldade em identificar a classe minoritária sugere que a estrutura das árvores está demasiado focada na predominância da classe 1, exigindo técnicas de balanceamento de pesos para melhorar a sua robustez.

* Gradient Boosting:
Este algoritmo mostrou maior eficácia que o Random Forest, alcançando 46% de Recall na classe 0 e 75% na classe 1. A sua construção sequencial permitiu capturar padrões mais subtis.

A AUC de 80% demonstra que o modelo possui uma alta capacidade de discriminação entre cafés especiais e comerciais. Já a acurácia de 67% é um reflexo do limiar de decisão de 0.5 que utilizamos.( modelo SVM, com probability=True O padrão no Scikit-Learn é 0.5). Em um cenário de desbalanceamento de classes, a acurácia é uma métrica limitada.
"""

